@startuml

left to right direction
actor user as us
actor system as sys


    usecase "Ingresar al sistema" as UC1

rectangle Armario{
    usecase "Escoger ropa" as UC2
}

    usecase "Validar información" as UC4
    usecase "Mostrar resultado" as UC5
    usecase "Salir" as UC6
    usecase "Mostrar menú" as UC7

us --> UC1

UC1 --> UC7
UC7 <-- sys

UC7 --> UC2
UC7 --> UC6

UC2 --> UC4
UC4 <--- sys

UC4 --> UC5


@enduml
